### ISSUE TITLE
Autocorrelation Function

### ISSUE THREAD

**Issue by adammwilson** [bioXgeo/geodiv#1]
Consider using a raster-based distance metric in the spatial autocorrelation function instead of the slower extract() based method.  I've developed one here https://github.com/AdamWilsonLab/rasterAutocorr that works quite well and I think will be much faster.  I'm happy to include that code in this package and stop development of the rasterAutocorr package.

**Comment by AnnieCooper** [comment]
I switched the functions in the aacf and fourier .R scripts to use a distance metric instead, so all functions are now way faster. Thanks for the link!
