### ISSUE TITLE
How to retrieve surface area en square meters ?

### ISSUE THREAD

**Issue by paul-carteron** [bioXgeo/geodiv#7]
Hello,
I am trying to calculate the surface of a landscape using a digital elevation model. I use your function `surface_area(x)`.
The results of this function depend on the input resolution of the raster. I guess it is as the definition says a "scaled surface area". Is there a solution to calculate the surface in square meters from the scaled surface area? Or more
Thanks in advance

**Comment by adammwilson** [comment]
The [`area()` function in the raster package](https://www.rdocumentation.org/packages/raster/versions/3.5-15/topics/area) will compute the 2D area of a pixel (assuming it's flat).  

Also, the [`sdr()` function in this package](https://rdrr.io/cran/geodiv/man/sdr.html) returns the surface area ratio of a raster - which could be multiplied with the output of `raster::area()` to get the area in real units.
