### ISSUE TITLE
Error in Sa calculation

### ISSUE THREAD

**Issue by skallagrimmson** [bioXgeo/geodiv#8]
@AnnieCooper 

I think there is an error in the calculation of Sa, which only plays a role in rasters with a lot of NA values. 

```
zbar <- mean(z, na.rm = TRUE)
  N <- length(z)

  val <- sum(abs(z - zbar), na.rm = TRUE) / N
```
while mean() excludes na's, length() does include all items in the list, including na's (as far as I know). 

Best wishes,

Eduard

edit: also in Ssk and Sku

**Comment by adammwilson** [comment]
Thanks for reporting this. I agree it's an error and I've corrected it [in the development branch](https://github.com/bioXgeo/geodiv/blob/af3d7500077f2216312db8172a26b5f0089bfc67/R/basics.R#L28).  You can install this corrected version with `devtools::install_github("bioXgeo/geodiv",ref = "dev")`

**Comment by AnnieCooper** [comment]
Thanks Eduard for reporting this, and Adam for correcting the error on the development branch. I have merged the changes made in the dev branch and fixed the errors in Ssk and Sku as well. The package version on CRAN is now updated with these changes.
